version: '2'

services:
    backend:
        build:
            context: backend
            args:
                - NODE_ENV=local
        ports:
            - "3001:3001"
        volumes:
            - ./backend/code:/app/code

    frontend:
        build:
            context: frontend
            args:
                - NODE_ENV=local
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/app/src
